tasks:
  - name: Setup & Run
    init: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py seed
    command: |
      python manage.py runserver 0.0.0.0:8000

ports:
  - port: 8000
    onOpen: open-preview
    name: Postudio Server
