# Generated by Django 6.0.7 on 2026-07-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postudio', '0009_post_post_type_post_video_url_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
