# Generated by Django 6.0.7 on 2026-07-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postudio', '0010_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostHide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('post_id', models.CharField(max_length=500)),
            ],
        ),
    ]
